// priority: 0
const items = [
  '/expandedstorage:*_present/',
  '/libraryferret:*/',
  '/lootr:*/',
  '/mekanism:advanced_energy_cube/',
  '/mekanism:atomic_disassembler/',
  '/mekanism:basic_energy_cube/',
  '/mekanism:canteen/',
  '/mekanism:configurator/',
  '/mekanism:creative_energy_cube/',
  '/mekanism:electric_bow/',
  '/mekanism:elite_energy_cube/',
  '/mekanism:energy_tablet/',
  '/mekanism:flamethrower/',
  '/mekanism:free_runners/',
  '/mekanism:jetpack/',
  '/mekanism:network_reader/',
  '/mekanism:portable_teleporter/',
  '/mekanism:robit/',
  '/mekanism:scuba_tank/',
  '/mekanism:seismic_reader/',
  '/mekanism:ultimate_energy_cube/',
  'buildinggadgets:construction_block_dense',
  'buildinggadgets:construction_block_powder',
  'buildinggadgets:construction_block',
  'buildinggadgets:construction_chunk_dense',
  'buildinggadgets:construction_paste_container_creative',
  'buildinggadgets:construction_paste_container_t1',
  'buildinggadgets:construction_paste_container_t2',
  'buildinggadgets:construction_paste_container_t3',
  'buildinggadgets:construction_paste',
  'buildinggadgets:template',
  'create:copper_backtank_placeable',
  'create:copper_sheet',
  'create:crushed_aluminum_ore',
  'create:crushed_copper_ore',
  'create:crushed_gold_ore',
  'create:crushed_iron_ore',
  'create:crushed_lead_ore',
  'create:crushed_nickel_ore',
  'create:crushed_osmium_ore',
  'create:crushed_platinum_ore',
  'create:crushed_quicksilver_ore',
  'create:crushed_silver_ore',
  'create:crushed_tin_ore',
  'create:crushed_uranium_ore',
  'create:golden_sheet',
  'create:incomplete_precision_mechanism',
  'create:incomplete_track',
  'create:iron_sheet',
  'create:unprocessed_obsidian_sheet',
  'createaddition:accumulator',
  'createaddition:brass_rod',
  'createaddition:capacitor',
  'createaddition:connector',
  'createaddition:copper_rod',
  'createaddition:copper_spool',
  'createaddition:copper_wire',
  'createaddition:diamond_grit',
  'createaddition:gold_rod',
  'createaddition:gold_spool',
  'createaddition:gold_wire',
  'createaddition:iron_rod',
  'createaddition:iron_wire',
  'createaddition:redstone_relay',
  'createaddition:rolling_mill',
  'createaddition:spool',
  'createaddition:tesla_coil',
  'createaddition:zinc_sheet',
  'decorative_blocks:blockstate_copy_item',
  'dimstorage:dim_core',
  'dimstorage:dim_wall',
  'dimstorage:solid_dim_core',
  'enderchests:ender_pouch',
  'expandedstorage:candy_cane_mini_present_with_sparrow',
  'expandedstorage:candy_cane_mini_present',
  'expandedstorage:green_mini_present_with_sparrow',
  'expandedstorage:green_mini_present',
  'expandedstorage:lavender_mini_present_with_sparrow',
  'expandedstorage:lavender_mini_present',
  'expandedstorage:old_diamond_chest',
  'expandedstorage:old_gold_chest',
  'expandedstorage:old_iron_chest',
  'expandedstorage:old_netherite_chest',
  'expandedstorage:old_obsidian_chest',
  'expandedstorage:old_wood_chest',
  'expandedstorage:pink_amethyst_mini_present_with_sparrow',
  'expandedstorage:pink_amethyst_mini_present',
  'expandedstorage:pumpkin_chest',
  'expandedstorage:pumpkin_mini_chest_with_sparrow',
  'expandedstorage:pumpkin_mini_chest',
  'expandedstorage:red_mini_present_with_sparrow',
  'expandedstorage:red_mini_present',
  'expandedstorage:vanilla_wood_mini_chest_with_sparrow',
  'expandedstorage:vanilla_wood_mini_chest',
  'expandedstorage:white_mini_present_with_sparrow',
  'expandedstorage:white_mini_present',
  'expandedstorage:wood_mini_chest_with_sparrow',
  'ftbquests:barrier',
  'ftbquests:custom_icon',
  'ftbquests:detector',
  'ftbquests:lootcrate',
  'ftbquests:missing_item',
  'ftbquests:stage_barrier',
  'immersiveengineering:coal_coke',
  'immersiveengineering:coke',
  'immersiveengineering:deepslate_ore_lead',
  'immersiveengineering:deepslate_ore_nickel',
  'immersiveengineering:deepslate_ore_silver',
  'immersiveengineering:deepslate_ore_uranium',
  'immersiveengineering:dust_constantan',
  'immersiveengineering:dust_copper',
  'immersiveengineering:dust_electrum',
  'immersiveengineering:dust_gold',
  'immersiveengineering:dust_iron',
  'immersiveengineering:dust_lead',
  'immersiveengineering:dust_nickel',
  'immersiveengineering:dust_silver',
  'immersiveengineering:dust_uranium',
  'immersiveengineering:dust_wood',
  'immersiveengineering:fake_icon_birthday',
  'immersiveengineering:fake_icon_coresample',
  'immersiveengineering:fake_icon_drillbreak',
  'immersiveengineering:fake_icon_lucky',
  'immersiveengineering:fake_icon_ravenholm',
  'immersiveengineering:ingot_constantan',
  'immersiveengineering:ingot_electrum',
  'immersiveengineering:ingot_lead',
  'immersiveengineering:ingot_nickel',
  'immersiveengineering:ingot_silver',
  'immersiveengineering:ingot_uranium',
  'immersiveengineering:nugget_constantan',
  'immersiveengineering:nugget_copper',
  'immersiveengineering:nugget_electrum',
  'immersiveengineering:nugget_lead',
  'immersiveengineering:nugget_nickel',
  'immersiveengineering:nugget_silver',
  'immersiveengineering:nugget_uranium',
  'immersiveengineering:ore_lead',
  'immersiveengineering:ore_nickel',
  'immersiveengineering:ore_silver',
  'immersiveengineering:ore_uranium',
  'immersiveengineering:plate_constantan',
  'immersiveengineering:plate_copper',
  'immersiveengineering:plate_electrum',
  'immersiveengineering:plate_gold',
  'immersiveengineering:plate_iron',
  'immersiveengineering:plate_lead',
  'immersiveengineering:plate_nickel',
  'immersiveengineering:plate_silver',
  'immersiveengineering:plate_uranium',
  'immersiveengineering:raw_block_uranium',
  'immersiveengineering:raw_lead',
  'immersiveengineering:raw_nickel',
  'immersiveengineering:raw_silver',
  'immersiveengineering:raw_uranium',
  'immersiveengineering:sawdust',
  'immersiveengineering:shader_bag_common',
  'immersiveengineering:shader_bag_epic',
  'immersiveengineering:shader_bag_ie_masterwork',
  'immersiveengineering:shader_bag_rare',
  'immersiveengineering:shader_bag_uncommon',
  'immersiveengineering:sheetmetal_uranium',
  'immersiveengineering:slab_sheetmetal_uranium',
  'immersiveengineering:slab_storage_uranium',
  'immersiveengineering:slag',
  'immersiveengineering:storage_constantan',
  'immersiveengineering:storage_electrum',
  'immersiveengineering:storage_lead',
  'immersiveengineering:storage_nickel',
  'immersiveengineering:storage_silver',
  'immersiveengineering:storage_steel',
  'immersiveengineering:storage_uranium',
  'immersiveengineering:watermill',
  'immersiveengineering:waterwheel_segment',
  'immersiveengineering:windmill_blade',
  'immersiveengineering:windmill_sail',
  'immersiveengineering:windmill',
  'industrialforegoing:diamond_gear',
  'industrialforegoing:dryrubber',
  'industrialforegoing:gold_gear',
  'industrialforegoing:iron_gear',
  'industrialforegoing:latex_processing_unit',
  'industrialforegoing:plastic',
  'industrialforegoing:tinydryrubber',
  'industrialforegoing:transporter',
  'kubejs:incomplete_hammer',
  'kubejs:incomplete_redstone_servo',
  'kubejs:incomplete_rf_coil',
  'mekanism:advanced_chemical_tank',
  'mekanism:advanced_combining_factory',
  'mekanism:advanced_compressing_factory',
  'mekanism:advanced_control_circuit',
  'mekanism:advanced_crushing_factory',
  'mekanism:advanced_energy_cube',
  'mekanism:advanced_enriching_factory',
  'mekanism:advanced_fluid_tank',
  'mekanism:advanced_induction_cell',
  'mekanism:advanced_induction_provider',
  'mekanism:advanced_infusing_factory',
  'mekanism:advanced_injecting_factory',
  'mekanism:advanced_logistical_transporter',
  'mekanism:advanced_mechanical_pipe',
  'mekanism:advanced_pressurized_tube',
  'mekanism:advanced_purifying_factory',
  'mekanism:advanced_sawing_factory',
  'mekanism:advanced_smelting_factory',
  'mekanism:advanced_thermodynamic_conductor',
  'mekanism:advanced_tier_installer',
  'mekanism:advanced_universal_cable',
  'mekanism:alloy_atomic',
  'mekanism:alloy_infused',
  'mekanism:alloy_reinforced',
  'mekanism:antiprotonic_nucleosynthesizer',
  'mekanism:atomic_disassembler',
  'mekanism:basic_chemical_tank',
  'mekanism:basic_combining_factory',
  'mekanism:basic_compressing_factory',
  'mekanism:basic_control_circuit',
  'mekanism:basic_crushing_factory',
  'mekanism:basic_energy_cube',
  'mekanism:basic_enriching_factory',
  'mekanism:basic_fluid_tank',
  'mekanism:basic_induction_cell',
  'mekanism:basic_induction_provider',
  'mekanism:basic_infusing_factory',
  'mekanism:basic_injecting_factory',
  'mekanism:basic_logistical_transporter',
  'mekanism:basic_mechanical_pipe',
  'mekanism:basic_pressurized_tube',
  'mekanism:basic_purifying_factory',
  'mekanism:basic_sawing_factory',
  'mekanism:basic_smelting_factory',
  'mekanism:basic_thermodynamic_conductor',
  'mekanism:basic_tier_installer',
  'mekanism:basic_universal_cable',
  'mekanism:bio_fuel',
  'mekanism:block_bronze',
  'mekanism:block_charcoal',
  'mekanism:block_fluorite',
  'mekanism:block_lead',
  'mekanism:block_osmium',
  'mekanism:block_raw_lead',
  'mekanism:block_raw_osmium',
  'mekanism:block_raw_tin',
  'mekanism:block_raw_uranium',
  'mekanism:block_refined_glowstone',
  'mekanism:block_refined_obsidian',
  'mekanism:block_salt',
  'mekanism:block_steel',
  'mekanism:block_tin',
  'mekanism:block_uranium',
  'mekanism:boiler_casing',
  'mekanism:boiler_valve',
  'mekanism:bounding_block',
  'mekanism:brine_bucket',
  'mekanism:canteen',
  'mekanism:cardboard_box',
  'mekanism:chargepad',
  'mekanism:chemical_crystallizer',
  'mekanism:chemical_dissolution_chamber',
  'mekanism:chemical_infuser',
  'mekanism:chemical_injection_chamber',
  'mekanism:chemical_oxidizer',
  'mekanism:chemical_washer',
  'mekanism:chlorine_bucket',
  'mekanism:clump_copper',
  'mekanism:clump_gold',
  'mekanism:clump_iron',
  'mekanism:clump_lead',
  'mekanism:clump_osmium',
  'mekanism:clump_tin',
  'mekanism:clump_uranium',
  'mekanism:combiner',
  'mekanism:configuration_card',
  'mekanism:configurator',
  'mekanism:crafting_formula',
  'mekanism:creative_bin',
  'mekanism:creative_chemical_tank',
  'mekanism:creative_energy_cube',
  'mekanism:creative_fluid_tank',
  'mekanism:crusher',
  'mekanism:crystal_copper',
  'mekanism:crystal_gold',
  'mekanism:crystal_iron',
  'mekanism:crystal_lead',
  'mekanism:crystal_osmium',
  'mekanism:crystal_tin',
  'mekanism:crystal_uranium',
  'mekanism:deepslate_fluorite_ore',
  'mekanism:deepslate_lead_ore',
  'mekanism:deepslate_osmium_ore',
  'mekanism:deepslate_tin_ore',
  'mekanism:deepslate_uranium_ore',
  'mekanism:dictionary',
  'mekanism:digital_miner',
  'mekanism:dimensional_stabilizer',
  'mekanism:dirty_dust_copper',
  'mekanism:dirty_dust_gold',
  'mekanism:dirty_dust_iron',
  'mekanism:dirty_dust_lead',
  'mekanism:dirty_dust_osmium',
  'mekanism:dirty_dust_tin',
  'mekanism:dirty_dust_uranium',
  'mekanism:dirty_netherite_scrap',
  'mekanism:diversion_transporter',
  'mekanism:dosimeter',
  'mekanism:dust_bronze',
  'mekanism:dust_charcoal',
  'mekanism:dust_coal',
  'mekanism:dust_copper',
  'mekanism:dust_diamond',
  'mekanism:dust_emerald',
  'mekanism:dust_fluorite',
  'mekanism:dust_gold',
  'mekanism:dust_iron',
  'mekanism:dust_lapis_lazuli',
  'mekanism:dust_lead',
  'mekanism:dust_lithium',
  'mekanism:dust_netherite',
  'mekanism:dust_obsidian',
  'mekanism:dust_osmium',
  'mekanism:dust_quartz',
  'mekanism:dust_refined_obsidian',
  'mekanism:dust_steel',
  'mekanism:dust_sulfur',
  'mekanism:dust_tin',
  'mekanism:dust_uranium',
  'mekanism:dye_base',
  'mekanism:dynamic_tank',
  'mekanism:dynamic_valve',
  'mekanism:electric_bow',
  'mekanism:electric_pump',
  'mekanism:electrolytic_core',
  'mekanism:electrolytic_separator',
  'mekanism:elite_chemical_tank',
  'mekanism:elite_combining_factory',
  'mekanism:elite_compressing_factory',
  'mekanism:elite_control_circuit',
  'mekanism:elite_crushing_factory',
  'mekanism:elite_energy_cube',
  'mekanism:elite_enriching_factory',
  'mekanism:elite_fluid_tank',
  'mekanism:elite_induction_cell',
  'mekanism:elite_induction_provider',
  'mekanism:elite_infusing_factory',
  'mekanism:elite_injecting_factory',
  'mekanism:elite_logistical_transporter',
  'mekanism:elite_mechanical_pipe',
  'mekanism:elite_pressurized_tube',
  'mekanism:elite_purifying_factory',
  'mekanism:elite_sawing_factory',
  'mekanism:elite_smelting_factory',
  'mekanism:elite_thermodynamic_conductor',
  'mekanism:elite_tier_installer',
  'mekanism:elite_universal_cable',
  'mekanism:energized_smelter',
  'mekanism:energy_tablet',
  'mekanism:enriched_carbon',
  'mekanism:enriched_diamond',
  'mekanism:enriched_gold',
  'mekanism:enriched_iron',
  'mekanism:enriched_redstone',
  'mekanism:enriched_refined_obsidian',
  'mekanism:enriched_tin',
  'mekanism:enrichment_chamber',
  'mekanism:ethene_bucket',
  'mekanism:flamethrower',
  'mekanism:fluidic_plenisher',
  'mekanism:fluorite_gem',
  'mekanism:fluorite_ore',
  'mekanism:formulaic_assemblicator',
  'mekanism:free_runners_armored',
  'mekanism:free_runners',
  'mekanism:fuelwood_heater',
  'mekanism:gauge_dropper',
  'mekanism:geiger_counter',
  'mekanism:hazmat_boots',
  'mekanism:hazmat_gown',
  'mekanism:hazmat_mask',
  'mekanism:hazmat_pants',
  'mekanism:hdpe_elytra',
  'mekanism:hdpe_pellet',
  'mekanism:hdpe_rod',
  'mekanism:hdpe_sheet',
  'mekanism:hdpe_stick',
  'mekanism:heavy_water_bucket',
  'mekanism:hydrofluoric_acid_bucket',
  'mekanism:hydrogen_bucket',
  'mekanism:hydrogen_chloride_bucket',
  'mekanism:induction_casing',
  'mekanism:induction_port',
  'mekanism:industrial_alarm',
  'mekanism:ingot_bronze',
  'mekanism:ingot_lead',
  'mekanism:ingot_osmium',
  'mekanism:ingot_refined_glowstone',
  'mekanism:ingot_refined_obsidian',
  'mekanism:ingot_steel',
  'mekanism:ingot_tin',
  'mekanism:ingot_uranium',
  'mekanism:isotopic_centrifuge',
  'mekanism:jetpack_armored',
  'mekanism:jetpack',
  'mekanism:laser_amplifier',
  'mekanism:laser_tractor_beam',
  'mekanism:laser',
  'mekanism:lead_ore',
  'mekanism:lithium_bucket',
  'mekanism:logistical_sorter',
  'mekanism:metallurgic_infuser',
  'mekanism:module_charge_distribution_unit',
  'mekanism:module_dosimeter_unit',
  'mekanism:module_geiger_unit',
  'mekanism:module_gravitational_modulating_unit',
  'mekanism:module_inhalation_purification_unit',
  'mekanism:module_laser_dissipation_unit',
  'mekanism:module_nutritional_injection_unit',
  'mekanism:module_radiation_shielding_unit',
  'mekanism:module_vein_mining_unit',
  'mekanism:network_reader',
  'mekanism:nugget_bronze',
  'mekanism:nugget_lead',
  'mekanism:nugget_osmium',
  'mekanism:nugget_refined_glowstone',
  'mekanism:nugget_refined_obsidian',
  'mekanism:nugget_steel',
  'mekanism:nugget_tin',
  'mekanism:nugget_uranium',
  'mekanism:nutritional_liquifier',
  'mekanism:nutritional_paste_bucket',
  'mekanism:oredictionificator',
  'mekanism:osmium_compressor',
  'mekanism:osmium_ore',
  'mekanism:oxygen_bucket',
  'mekanism:painting_machine',
  'mekanism:pellet_antimatter',
  'mekanism:pellet_plutonium',
  'mekanism:pellet_polonium',
  'mekanism:personal_barrel',
  'mekanism:personal_chest',
  'mekanism:pigment_extractor',
  'mekanism:pigment_mixer',
  'mekanism:portable_qio_dashboard',
  'mekanism:portable_teleporter',
  'mekanism:precision_sawmill',
  'mekanism:pressure_disperser',
  'mekanism:pressurized_reaction_chamber',
  'mekanism:purification_chamber',
  'mekanism:qio_dashboard',
  'mekanism:qio_drive_array',
  'mekanism:qio_drive_base',
  'mekanism:qio_drive_hyper_dense',
  'mekanism:qio_drive_supermassive',
  'mekanism:qio_drive_time_dilating',
  'mekanism:qio_exporter',
  'mekanism:qio_importer',
  'mekanism:qio_redstone_adapter',
  'mekanism:quantum_entangloporter',
  'mekanism:radioactive_waste_barrel',
  'mekanism:raw_lead',
  'mekanism:raw_osmium',
  'mekanism:raw_tin',
  'mekanism:raw_uranium',
  'mekanism:reprocessed_fissile_fragment',
  'mekanism:resistive_heater',
  'mekanism:restrictive_transporter',
  'mekanism:robit',
  'mekanism:rotary_condensentrator',
  'mekanism:salt',
  'mekanism:sawdust',
  'mekanism:scuba_mask',
  'mekanism:scuba_tank',
  'mekanism:security_desk',
  'mekanism:seismic_reader',
  'mekanism:seismic_vibrator',
  'mekanism:shard_copper',
  'mekanism:shard_gold',
  'mekanism:shard_iron',
  'mekanism:shard_lead',
  'mekanism:shard_osmium',
  'mekanism:shard_tin',
  'mekanism:shard_uranium',
  'mekanism:sodium_bucket',
  'mekanism:solar_neutron_activator',
  'mekanism:sps_casing',
  'mekanism:sps_port',
  'mekanism:steam_bucket',
  'mekanism:steel_casing',
  'mekanism:structural_glass',
  'mekanism:substrate',
  'mekanism:sulfur_dioxide_bucket',
  'mekanism:sulfur_trioxide_bucket',
  'mekanism:sulfuric_acid_bucket',
  'mekanism:supercharged_coil',
  'mekanism:superheated_sodium_bucket',
  'mekanism:superheating_element',
  'mekanism:teleportation_core',
  'mekanism:teleporter_frame',
  'mekanism:teleporter',
  'mekanism:thermal_evaporation_block',
  'mekanism:thermal_evaporation_controller',
  'mekanism:thermal_evaporation_valve',
  'mekanism:tin_ore',
  'mekanism:ultimate_chemical_tank',
  'mekanism:ultimate_combining_factory',
  'mekanism:ultimate_compressing_factory',
  'mekanism:ultimate_control_circuit',
  'mekanism:ultimate_crushing_factory',
  'mekanism:ultimate_energy_cube',
  'mekanism:ultimate_enriching_factory',
  'mekanism:ultimate_fluid_tank',
  'mekanism:ultimate_induction_cell',
  'mekanism:ultimate_induction_provider',
  'mekanism:ultimate_infusing_factory',
  'mekanism:ultimate_injecting_factory',
  'mekanism:ultimate_logistical_transporter',
  'mekanism:ultimate_mechanical_pipe',
  'mekanism:ultimate_pressurized_tube',
  'mekanism:ultimate_purifying_factory',
  'mekanism:ultimate_sawing_factory',
  'mekanism:ultimate_smelting_factory',
  'mekanism:ultimate_thermodynamic_conductor',
  'mekanism:ultimate_tier_installer',
  'mekanism:ultimate_universal_cable',
  'mekanism:upgrade_anchor',
  'mekanism:upgrade_energy',
  'mekanism:upgrade_filter',
  'mekanism:upgrade_gas',
  'mekanism:upgrade_muffling',
  'mekanism:upgrade_speed',
  'mekanism:upgrade_stone_generator',
  'mekanism:uranium_hexafluoride_bucket',
  'mekanism:uranium_ore',
  'mekanism:uranium_oxide_bucket',
  'mekanism:yellow_cake_uranium',
  'minecraft:barrier',
  'minecraft:chest',
  'minecraft:debug_stick',
  'minecraft:knowledge_book',
  'minecraft:light',
  'minecraft:sculk_sensor',
  'moreminecarts:silica_steel_mix',
  'pipez:gas_pipe',
  'refinedstorage:black_controller',
  'refinedstorage:black_crafter_manager',
  'refinedstorage:black_crafter',
  'refinedstorage:black_crafting_grid',
  'refinedstorage:black_crafting_monitor',
  'refinedstorage:black_creative_controller',
  'refinedstorage:black_detector',
  'refinedstorage:black_disk_manipulator',
  'refinedstorage:black_fluid_grid',
  'refinedstorage:black_grid',
  'refinedstorage:black_network_receiver',
  'refinedstorage:black_network_transmitter',
  'refinedstorage:black_pattern_grid',
  'refinedstorage:black_relay',
  'refinedstorage:black_security_manager',
  'refinedstorage:black_wireless_transmitter',
  'refinedstorage:blue_controller',
  'refinedstorage:blue_crafter_manager',
  'refinedstorage:blue_crafter',
  'refinedstorage:blue_crafting_grid',
  'refinedstorage:blue_crafting_monitor',
  'refinedstorage:blue_creative_controller',
  'refinedstorage:blue_detector',
  'refinedstorage:blue_disk_manipulator',
  'refinedstorage:blue_fluid_grid',
  'refinedstorage:blue_grid',
  'refinedstorage:blue_network_receiver',
  'refinedstorage:blue_network_transmitter',
  'refinedstorage:blue_pattern_grid',
  'refinedstorage:blue_relay',
  'refinedstorage:blue_security_manager',
  'refinedstorage:blue_wireless_transmitter',
  'refinedstorage:brown_controller',
  'refinedstorage:brown_crafter_manager',
  'refinedstorage:brown_crafter',
  'refinedstorage:brown_crafting_grid',
  'refinedstorage:brown_crafting_monitor',
  'refinedstorage:brown_creative_controller',
  'refinedstorage:brown_detector',
  'refinedstorage:brown_disk_manipulator',
  'refinedstorage:brown_fluid_grid',
  'refinedstorage:brown_grid',
  'refinedstorage:brown_network_receiver',
  'refinedstorage:brown_network_transmitter',
  'refinedstorage:brown_pattern_grid',
  'refinedstorage:brown_relay',
  'refinedstorage:brown_security_manager',
  'refinedstorage:brown_wireless_transmitter',
  'refinedstorage:creative_controller',
  'refinedstorage:creative_fluid_storage_block',
  'refinedstorage:creative_fluid_storage_disk',
  'refinedstorage:creative_portable_grid',
  'refinedstorage:creative_storage_block',
  'refinedstorage:creative_storage_disk',
  'refinedstorage:creative_wireless_crafting_monitor',
  'refinedstorage:creative_wireless_fluid_grid',
  'refinedstorage:creative_wireless_grid',
  'refinedstorage:cyan_controller',
  'refinedstorage:cyan_crafter_manager',
  'refinedstorage:cyan_crafter',
  'refinedstorage:cyan_crafting_grid',
  'refinedstorage:cyan_crafting_monitor',
  'refinedstorage:cyan_creative_controller',
  'refinedstorage:cyan_detector',
  'refinedstorage:cyan_disk_manipulator',
  'refinedstorage:cyan_fluid_grid',
  'refinedstorage:cyan_grid',
  'refinedstorage:cyan_network_receiver',
  'refinedstorage:cyan_network_transmitter',
  'refinedstorage:cyan_pattern_grid',
  'refinedstorage:cyan_relay',
  'refinedstorage:cyan_security_manager',
  'refinedstorage:cyan_wireless_transmitter',
  'refinedstorage:gray_controller',
  'refinedstorage:gray_crafter_manager',
  'refinedstorage:gray_crafter',
  'refinedstorage:gray_crafting_grid',
  'refinedstorage:gray_crafting_monitor',
  'refinedstorage:gray_creative_controller',
  'refinedstorage:gray_detector',
  'refinedstorage:gray_disk_manipulator',
  'refinedstorage:gray_fluid_grid',
  'refinedstorage:gray_grid',
  'refinedstorage:gray_network_receiver',
  'refinedstorage:gray_network_transmitter',
  'refinedstorage:gray_pattern_grid',
  'refinedstorage:gray_relay',
  'refinedstorage:gray_security_manager',
  'refinedstorage:gray_wireless_transmitter',
  'refinedstorage:green_controller',
  'refinedstorage:green_crafter_manager',
  'refinedstorage:green_crafter',
  'refinedstorage:green_crafting_grid',
  'refinedstorage:green_crafting_monitor',
  'refinedstorage:green_creative_controller',
  'refinedstorage:green_detector',
  'refinedstorage:green_disk_manipulator',
  'refinedstorage:green_fluid_grid',
  'refinedstorage:green_grid',
  'refinedstorage:green_network_receiver',
  'refinedstorage:green_network_transmitter',
  'refinedstorage:green_pattern_grid',
  'refinedstorage:green_relay',
  'refinedstorage:green_security_manager',
  'refinedstorage:green_wireless_transmitter',
  'refinedstorage:light_gray_controller',
  'refinedstorage:light_gray_crafter_manager',
  'refinedstorage:light_gray_crafter',
  'refinedstorage:light_gray_crafting_grid',
  'refinedstorage:light_gray_crafting_monitor',
  'refinedstorage:light_gray_creative_controller',
  'refinedstorage:light_gray_detector',
  'refinedstorage:light_gray_disk_manipulator',
  'refinedstorage:light_gray_fluid_grid',
  'refinedstorage:light_gray_grid',
  'refinedstorage:light_gray_network_receiver',
  'refinedstorage:light_gray_network_transmitter',
  'refinedstorage:light_gray_pattern_grid',
  'refinedstorage:light_gray_relay',
  'refinedstorage:light_gray_security_manager',
  'refinedstorage:light_gray_wireless_transmitter',
  'refinedstorage:lime_controller',
  'refinedstorage:lime_crafter_manager',
  'refinedstorage:lime_crafter',
  'refinedstorage:lime_crafting_grid',
  'refinedstorage:lime_crafting_monitor',
  'refinedstorage:lime_creative_controller',
  'refinedstorage:lime_detector',
  'refinedstorage:lime_disk_manipulator',
  'refinedstorage:lime_fluid_grid',
  'refinedstorage:lime_grid',
  'refinedstorage:lime_network_receiver',
  'refinedstorage:lime_network_transmitter',
  'refinedstorage:lime_pattern_grid',
  'refinedstorage:lime_relay',
  'refinedstorage:lime_security_manager',
  'refinedstorage:lime_wireless_transmitter',
  'refinedstorage:magenta_controller',
  'refinedstorage:magenta_crafter_manager',
  'refinedstorage:magenta_crafter',
  'refinedstorage:magenta_crafting_grid',
  'refinedstorage:magenta_crafting_monitor',
  'refinedstorage:magenta_creative_controller',
  'refinedstorage:magenta_detector',
  'refinedstorage:magenta_disk_manipulator',
  'refinedstorage:magenta_fluid_grid',
  'refinedstorage:magenta_grid',
  'refinedstorage:magenta_network_receiver',
  'refinedstorage:magenta_network_transmitter',
  'refinedstorage:magenta_pattern_grid',
  'refinedstorage:magenta_relay',
  'refinedstorage:magenta_security_manager',
  'refinedstorage:magenta_wireless_transmitter',
  'refinedstorage:orange_controller',
  'refinedstorage:orange_crafter_manager',
  'refinedstorage:orange_crafter',
  'refinedstorage:orange_crafting_grid',
  'refinedstorage:orange_crafting_monitor',
  'refinedstorage:orange_creative_controller',
  'refinedstorage:orange_detector',
  'refinedstorage:orange_disk_manipulator',
  'refinedstorage:orange_fluid_grid',
  'refinedstorage:orange_grid',
  'refinedstorage:orange_network_receiver',
  'refinedstorage:orange_network_transmitter',
  'refinedstorage:orange_pattern_grid',
  'refinedstorage:orange_relay',
  'refinedstorage:orange_security_manager',
  'refinedstorage:orange_wireless_transmitter',
  'refinedstorage:pink_controller',
  'refinedstorage:pink_crafter_manager',
  'refinedstorage:pink_crafter',
  'refinedstorage:pink_crafting_grid',
  'refinedstorage:pink_crafting_monitor',
  'refinedstorage:pink_creative_controller',
  'refinedstorage:pink_detector',
  'refinedstorage:pink_disk_manipulator',
  'refinedstorage:pink_fluid_grid',
  'refinedstorage:pink_grid',
  'refinedstorage:pink_network_receiver',
  'refinedstorage:pink_network_transmitter',
  'refinedstorage:pink_pattern_grid',
  'refinedstorage:pink_relay',
  'refinedstorage:pink_security_manager',
  'refinedstorage:pink_wireless_transmitter',
  'refinedstorage:purple_controller',
  'refinedstorage:purple_crafter_manager',
  'refinedstorage:purple_crafter',
  'refinedstorage:purple_crafting_grid',
  'refinedstorage:purple_crafting_monitor',
  'refinedstorage:purple_creative_controller',
  'refinedstorage:purple_detector',
  'refinedstorage:purple_disk_manipulator',
  'refinedstorage:purple_fluid_grid',
  'refinedstorage:purple_grid',
  'refinedstorage:purple_network_receiver',
  'refinedstorage:purple_network_transmitter',
  'refinedstorage:purple_pattern_grid',
  'refinedstorage:purple_relay',
  'refinedstorage:purple_security_manager',
  'refinedstorage:purple_wireless_transmitter',
  'refinedstorage:red_controller',
  'refinedstorage:red_crafter_manager',
  'refinedstorage:red_crafter',
  'refinedstorage:red_crafting_grid',
  'refinedstorage:red_crafting_monitor',
  'refinedstorage:red_creative_controller',
  'refinedstorage:red_detector',
  'refinedstorage:red_disk_manipulator',
  'refinedstorage:red_fluid_grid',
  'refinedstorage:red_grid',
  'refinedstorage:red_network_receiver',
  'refinedstorage:red_network_transmitter',
  'refinedstorage:red_pattern_grid',
  'refinedstorage:red_relay',
  'refinedstorage:red_security_manager',
  'refinedstorage:red_wireless_transmitter',
  'refinedstorage:white_controller',
  'refinedstorage:white_crafter_manager',
  'refinedstorage:white_crafter',
  'refinedstorage:white_crafting_grid',
  'refinedstorage:white_crafting_monitor',
  'refinedstorage:white_creative_controller',
  'refinedstorage:white_detector',
  'refinedstorage:white_disk_manipulator',
  'refinedstorage:white_fluid_grid',
  'refinedstorage:white_grid',
  'refinedstorage:white_network_receiver',
  'refinedstorage:white_network_transmitter',
  'refinedstorage:white_pattern_grid',
  'refinedstorage:white_relay',
  'refinedstorage:white_security_manager',
  'refinedstorage:white_wireless_transmitter',
  'refinedstorage:yellow_controller',
  'refinedstorage:yellow_crafter_manager',
  'refinedstorage:yellow_crafter',
  'refinedstorage:yellow_crafting_grid',
  'refinedstorage:yellow_crafting_monitor',
  'refinedstorage:yellow_creative_controller',
  'refinedstorage:yellow_detector',
  'refinedstorage:yellow_disk_manipulator',
  'refinedstorage:yellow_fluid_grid',
  'refinedstorage:yellow_grid',
  'refinedstorage:yellow_network_receiver',
  'refinedstorage:yellow_network_transmitter',
  'refinedstorage:yellow_pattern_grid',
  'refinedstorage:yellow_relay',
  'refinedstorage:yellow_security_manager',
  'refinedstorage:yellow_wireless_transmitter',
  'rftoolsbase:crafting_card',
  'rftoolsbase:filter_module',
  'rftoolsbase:infused_enderpearl',
  'rftoolsbase:tablet_filled',
  'rftoolsbase:tablet',
  'thermal:beetroot_block',
  'thermal:carrot_block',
  'thermal:deepslate_ruby_ore',
  'thermal:deepslate_sapphire_ore',
  'thermal:drill_head',
  'thermal:emerald_gear',
  'thermal:lapis_gear',
  'thermal:potato_block',
  'thermal:quartz_gear',
  'thermal:ruby_block',
  'thermal:ruby_dust',
  'thermal:ruby_gear',
  'thermal:ruby_ore',
  'thermal:ruby',
  'thermal:sapphire_block',
  'thermal:sapphire_dust',
  'thermal:sapphire_gear',
  'thermal:sapphire_ore',
  'thermal:sapphire',
  'thermal:saw_blade',
  'titanium:block_asset_test',
  'titanium:block_test',
  'titanium:block_twenty_four_test',
  'titanium:creative_generator',
  'titanium:machine_test',
  'torchmaster:feral_flare_lantern',
  'torchmaster:frozen_pearl',
  Fluid.of('mekanism:brine'),
  Fluid.of('mekanism:chlorine'),
  Fluid.of('mekanism:ethene'),
  Fluid.of('mekanism:flowing_brine'),
  Fluid.of('mekanism:heavy_water'),
  Fluid.of('mekanism:hydrofluoric_acid'),
  Fluid.of('mekanism:hydrogen_chloride'),
  Fluid.of('mekanism:hydrogen'),
  Fluid.of('mekanism:lithium'),
  Fluid.of('mekanism:nutritional_paste'),
  Fluid.of('mekanism:oxygen'),
  Fluid.of('mekanism:sodium'),
  Fluid.of('mekanism:steam'),
  Fluid.of('mekanism:sulfur_dioxide'),
  Fluid.of('mekanism:sulfur_trioxide'),
  Fluid.of('mekanism:sulfuric_acid'),
  Fluid.of('mekanism:superheated_sodium'),
  Fluid.of('mekanism:uranium_hexafluoride'),
  Fluid.of('mekanism:uranium_oxide'),
  Fluid.of('mekanism:flowing_chlorine'),
  Fluid.of('mekanism:flowing_ethene'),
  Fluid.of('mekanism:flowing_heavy_water'),
  Fluid.of('mekanism:flowing_hydrofluoric_acid'),
  Fluid.of('mekanism:flowing_hydrogen_chloride'),
  Fluid.of('mekanism:flowing_hydrogen'),
  Fluid.of('mekanism:flowing_lithium'),
  Fluid.of('mekanism:flowing_nutritional_paste'),
  Fluid.of('mekanism:flowing_oxygen'),
  Fluid.of('mekanism:flowing_sodium'),
  Fluid.of('mekanism:flowing_steam'),
  Fluid.of('mekanism:flowing_sulfur_dioxide'),
  Fluid.of('mekanism:flowing_sulfur_trioxide'),
  Fluid.of('mekanism:flowing_sulfuric_acid'),
  Fluid.of('mekanism:flowing_superheated_sodium'),
  Fluid.of('mekanism:flowing_uranium_hexafluoride'),
  Fluid.of('mekanism:flowing_uranium_oxide'),
  Item.of('immersiveengineering:blueprint', '{blueprint:"electrode"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"ecologics:long_sliding"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"ecologics:sliding"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"infernalexp:infection"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"infernalexp:long_infection"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"infernalexp:long_luminous"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"infernalexp:luminous"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"infernalexp:strong_infection"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"infernalexp:strong_luminous"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:fire_resistance"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:harming"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:healing"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:invisibility"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:leaping"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_fire_resistance"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_invisibility"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_leaping"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_night_vision"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_poison"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_regeneration"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_slow_falling"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_slowness"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_strength"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_swiftness"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_turtle_master"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_water_breathing"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:long_weakness"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:luck"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:night_vision"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:poison"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:regeneration"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:slow_falling"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:slowness"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:strength"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:strong_harming"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:strong_healing"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:strong_leaping"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:strong_poison"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:strong_regeneration"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:strong_slowness"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:strong_strength"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:strong_swiftness"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:strong_turtle_master"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:swiftness"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:turtle_master"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:water_breathing"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"minecraft:weakness"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"naturalist:forest_dasher"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"naturalist:glowing"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"naturalist:long_forest_dasher"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"naturalist:long_glowing"}'),
  Item.of('minecraft:lingering_potion', '{Potion:"naturalist:strong_forest_dasher"}'),
  Item.of('minecraft:splash_potion', '{Potion:"ecologics:long_sliding"}'),
  Item.of('minecraft:splash_potion', '{Potion:"ecologics:sliding"}'),
  Item.of('minecraft:splash_potion', '{Potion:"infernalexp:infection"}'),
  Item.of('minecraft:splash_potion', '{Potion:"infernalexp:long_infection"}'),
  Item.of('minecraft:splash_potion', '{Potion:"infernalexp:long_luminous"}'),
  Item.of('minecraft:splash_potion', '{Potion:"infernalexp:luminous"}'),
  Item.of('minecraft:splash_potion', '{Potion:"infernalexp:strong_infection"}'),
  Item.of('minecraft:splash_potion', '{Potion:"infernalexp:strong_luminous"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:awkward"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:fire_resistance"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:harming"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:healing"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:invisibility"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:leaping"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_fire_resistance"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_invisibility"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_leaping"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_night_vision"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_poison"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_regeneration"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_slow_falling"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_slowness"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_strength"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_swiftness"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_turtle_master"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_water_breathing"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:long_weakness"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:luck"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:night_vision"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:poison"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:regeneration"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:slow_falling"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:slowness"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:strength"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:strong_harming"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:strong_healing"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:strong_leaping"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:strong_poison"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:strong_regeneration"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:strong_slowness"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:strong_strength"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:strong_swiftness"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:strong_turtle_master"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:swiftness"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:turtle_master"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:water_breathing"}'),
  Item.of('minecraft:splash_potion', '{Potion:"minecraft:weakness"}'),
  Item.of('minecraft:splash_potion', '{Potion:"naturalist:forest_dasher"}'),
  Item.of('minecraft:splash_potion', '{Potion:"naturalist:glowing"}'),
  Item.of('minecraft:splash_potion', '{Potion:"naturalist:long_forest_dasher"}'),
  Item.of('minecraft:splash_potion', '{Potion:"naturalist:long_glowing"}'),
  Item.of('minecraft:splash_potion', '{Potion:"naturalist:strong_forest_dasher"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"ecologics:long_sliding"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"ecologics:sliding"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"infernalexp:infection"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"infernalexp:long_infection"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"infernalexp:long_luminous"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"infernalexp:luminous"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"infernalexp:strong_infection"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"infernalexp:strong_luminous"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:fire_resistance"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:harming"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:healing"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:invisibility"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:leaping"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_fire_resistance"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_invisibility"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_leaping"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_night_vision"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_poison"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_regeneration"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_slow_falling"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_slowness"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_strength"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_swiftness"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_turtle_master"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_water_breathing"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:long_weakness"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:luck"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:night_vision"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:poison"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:regeneration"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:slow_falling"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:slowness"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:strength"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:strong_harming"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:strong_healing"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:strong_leaping"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:strong_poison"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:strong_regeneration"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:strong_slowness"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:strong_strength"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:strong_swiftness"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:strong_turtle_master"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:swiftness"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:turtle_master"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:water_breathing"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"minecraft:weakness"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"naturalist:forest_dasher"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"naturalist:glowing"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"naturalist:long_forest_dasher"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"naturalist:long_glowing"}'),
  Item.of('minecraft:tipped_arrow', '{Potion:"naturalist:strong_forest_dasher"}'),
  'everycomp:all_woods',
  'mcjtylib:multipart',
  'supplementaries:bomb_blue_projectile',
  'supplementaries:bomb_projectile',
  'supplementaries:bomb_spiky_projectile',
];

onEvent('jei.hide.items', event => {
  items.forEach(x => {
    try {
      event.hide(x);
    } catch (e) {
      console.log(e);
    }
  });
});

onEvent('rei.hide.items', event => {
  items.forEach(x => {
    try {
      event.hide(x);
    } catch (e) {
      console.log(e);
    }
  });
});

onEvent('rei.remove.categories', event => {
  [
    'minecraft:plugins/tag',
    'mekanism:nutritional_liquifier',
    'mekanism:sps_casing',
    'mekanism:boiler_casing',
    'mekanism:energized_smelter',
  ].forEach(x => event.remove(x));
});
