
[general]
	#List of items to disallow from placing in the belt. (whitelist takes precedence)
	blacklist = []
	#List of items to force-allow placing in the belt. Takes precedence over blacklist.
	whitelist = ["upgrade_aquatic:white_bedroll", "upgrade_aquatic:orange_bedroll", "upgrade_aquatic:magenta_bedroll", "upgrade_aquatic:light_blue_bedroll", "upgrade_aquatic:yellow_bedroll", "upgrade_aquatic:lime_bedroll", "upgrade_aquatic:pink_bedroll", "upgrade_aquatic:gray_bedroll", "upgrade_aquatic:light_gray_bedroll", "upgrade_aquatic:cyan_bedroll", "upgrade_aquatic:purple_bedroll", "upgrade_aquatic:blue_bedroll", "upgrade_aquatic:brown_bedroll", "upgrade_aquatic:red_bedroll", "upgrade_aquatic:black_bedroll", "upgrade_aquatic:bedroll"]

