
#Miscellaneous
[general]
	#The maximum number of twigs that can be found in each chunk
	#Range: 0 ~ 256
	maxTwigsPerChunk = 1
	#Setting this to true will let players know that they can't break certain blocks without a certain tool
	showToolHelp = false
	#The chance (out of 100) that a bone can drop from the entities in 'boneDropMobs'.
	#Setting this to 0 disables this feature
	#Range: 0 ~ 100
	boneDropFromMobsChance = 50
	#A list of 'modid:block' that represent blocks that twigs can be placed on.
	twigPlacementBlacklist = ["minecraft:ice", "minecraft:packed_ice", "minecraft:bedrock"]
	#The chance (out of 100) for flint to be created via knapping.
	#e.g.: Setting to 75 means there is a 75% chance knapping will provide flint.
	#Range: 1 ~ 100
	flintKnappingChance = 45
	#Setting this to true prevents the ability to use stone tools, though you can still craft them for compatibility.
	removeStoneToolFunctionality = true
	#Setting this to true will allow you to replace pebbles like tall grass (more convenient for building, but loses the block forever
	arePebblesReplaceable = true
	#A string of dimensions in which pebbles should spawn. See the defaults for the format.
	dimensionWhitelist = ["minecraft:overworld", "minecraft:the_nether", "minecraft:the_end"]
	#The maximum number of pebbles that can be found in each chunk
	#Range: 0 ~ 256
	maxPebblesPerChunk = 3
	#A list of 'modid:block' that represent blocks that pebbles can be placed on.
	pebblePlacementBlacklist = ["minecraft:ice", "minecraft:packed_ice", "minecraft:bedrock"]
	#Enabling this causes all entities to drop additional bones when killed
	allEntitiesDropBones = false
	#The chance (out of 100) for bone to be created via knapping.
	#e.g.: Setting to 75 means there is a 75% chance knapping will provide a bone shard.
	#Range: 1 ~ 100
	boneShardKnappingChance = 99
	#Setting this to true will make ground blocks (e.g. sand, dirt, gravel) harder to break without the correct tool.
	makeGroundBlocksHarder = true
	#Setting this to true prevents the ability to use wooden tools, though you can still craft them for compatibility.
	removeWoodenToolFunctionality = true

