
#A higher spawn weight will make the mob spawn more often.
#To prevent a certain mob from spawning, set its weight to 0.
["Mob Spawn Weights"]
	#Snail spawn weight
	#Range: 0 ~ 1000
	snailSpawnWeight = 5
	#Snake spawn weight
	#Range: 0 ~ 1000
	snakeSpawnWeight = 4
	#Coral Snake spawn weight
	#Range: 0 ~ 1000
	coralSnakeSpawnWeight = 4
	#Rattlesnake spawn weight
	#Range: 0 ~ 1000
	rattlesnakeSpawnWeight = 4
	#Bear spawn weight
	#Range: 0 ~ 1000
	bearSpawnWeight = 8
	#Deer spawn weight
	#Range: 0 ~ 1000
	deerSpawnWeight = 8
	#Firefly spawn weight
	#Range: 0 ~ 1000
	fireflySpawnWeight = 8
	#Bluejay spawn weight
	#Range: 0 ~ 1000
	bluejaySpawnWeight = 8
	#Canary spawn weight
	#Range: 0 ~ 1000
	canarySpawnWeight = 8
	#Cardinal spawn weight
	#Range: 0 ~ 1000
	cardinalSpawnWeight = 8
	#Robin spawn weight
	#Range: 0 ~ 1000
	robinSpawnWeight = 8
	#Butterfly spawn weight
	#Range: 0 ~ 1000
	butterflySpawnWeight = 6
	#Rabbit spawn weight in forest biomes
	#Range: 0 ~ 1000
	forestRabbitSpawnWeight = 6
	#Fox spawn weight in forest biomes
	#Range: 0 ~ 1000
	forestFoxSpawnWeight = 6

