
#Mapper Settings
[mapper]
	#Enables the usage of Biome Colors on the mapper
	BiomeColors = true
	#Enables the creation of Death Waypoints
	DeathWaypoints = true

#Settings for the Minimap
[minimap]
	#X Position of the Minimap
	#Range: -500 ~ 500
	posX = 0
	#Y Position of the Minimap
	#Range: -500 ~ 500
	posY = 0
	#Is Minimap visible?
	visible = true
	#Set this to true and the minimap will spin in the direction you're facing
	Spin = false
	#Scale of the Minimap
	#Range: 0.25 ~ 4.0
	scale = 1.3999999999999977
	#Selected Style (don't change this manually)
	style = "Default"
	#Alignment of the Minimap
	#Allowed Values: TOP_LEFT, TOP, TOP_RIGHT, LEFT, CENTER, RIGHT, BOTTOM_LEFT, BOTTOM, BOTTOM_RIGHT
	alignment = "TOP_LEFT"

#Settings for the Compass (Unimplemented right now)
[compass]
	#X Position of the Compass
	#Range: -500 ~ 500
	posX = -128
	#Y Position of the Compass
	#Range: -500 ~ 500
	posY = 1
	#Is Compass visible?
	visible = false
	#Scale of the Compass
	#Range: 0.25 ~ 4.0
	scale = 1.0
	#Selected Style (don't change this manually)
	style = "default"
	#Alignment of the Compass
	#Allowed Values: TOP_LEFT, TOP, TOP_RIGHT, LEFT, CENTER, RIGHT, BOTTOM_LEFT, BOTTOM, BOTTOM_RIGHT
	alignment = "TOP"

