
#Miscellaneous
[miscellaneous]
	#Disables thunder storms, fixing glitched lighting from thunder and other side-effects
	enableStormTweak = false
	#Prints your death point in chat
	enableDeathPoint = false
	#Show food hunger & saturation on item hover
	#Allowed Values: NEVER, WITH_SHIFT, ALWAYS
	foodTooltipSetting = "NEVER"
	#Makes all anvil tool repairs always cost 1 level of XP
	enableCheapAnvilRepair = true
	#Show tool durability on item hover
	#Allowed Values: NEVER, WITH_SHIFT, ALWAYS
	durabilityTooltipSetting = "WITH_SHIFT"

#Block Tweaks
["block tweaks"]
	#A list of blocks to ignore, of form <modid:block>
	cropTweaksBlacklist = []
	#Allows more plants to be bonemealed
	enableBonemealTweak = true
	#Trees fall down (like, actually not just like lumbering). Credit to Tersnip's impl (oitsjustjo.se/u/5cCfruy1x)
	enableTreeChopDown = false
	#The number of logs above the one broken to trigger the chopdown effect
	#Range: > 1
	chopDownLogRequirement = 3
	#Allows for uneaten cake to drop on break
	enableCakeDrop = true
	#Allows the player to re-light certain blocks like Candles and Campfires (defined by the block using the `lit` blockstate) using torches or other items in the tag `vtweaks:ignition_item`
	enableTorchLighting = true
	#Allows for r-clicking to harvest most any (including mod) crops
	enableCropTweaks = true

#Enchantments
[enchantments]
	#Number of levels Imperishable costs to create in an anvil
	#Range: 1 ~ 40
	imperishableCost = 30
	#Should the lumbering enchantment also prune the leaves of a tree?
	lumberingCutsLeaves = true
	#Should the lumbering enchantment be strict about wood types?
	#e.g. if you're in a forest with mixed woods touching, should lumbering only break the same type of wood that was initially broken?
	lumberingIsStrictAboutWood = true
	#Enable the Imperishable enchantment for any breakable item
	enableImperishable = true
	#The maximum amount of logs lumbering can destroy
	#Range: > 1
	maxLumberCount = 1024
	#Feather Falling IV or above directs 100% of fall damage to boots
	enableFeatherFallTweak = true
	#Number of levels Lumbering costs to create in an anvil
	#Range: 1 ~ 40
	lumberingCost = 16
	#Enable the Lumbering enchantment for Axes
	enableLumbering = true

#Mob Tweaks
["mob tweaks"]
	#If set to "OWNER", this will prevent owners of pets from attacking their own pet. If set to "ALL", this prevents all players from attacking anyone's pet
	#Allowed Values: DISABLED, OWNER, ALL
	enablePetFriendlyFireTweak = "OWNER"
	#Any time a Baby Zombie (or Zombie Piglin) spawns, it will be replaced with an adult
	enableBabyZombieTweak = true
	#A list of dimensions (of form <modid:type>) to ignore when prevent surface mob spawns.
	peacefulSurfaceDimBlacklist = ["minecraft:the_nether", "minecraft:the_end"]
	#The amount of time (in Milliseconds) between plucks. Defaults to 10 minutes.
	#Range: 1 ~ 9223372036854775807
	featurePluckingCooldown = 600000
	#A data-driven way to make some special mobs with abilities, effects, specialized loot and more!
	enableChallengerMobs = false
	#Allows chicken feathers to be plucked w/ shears
	enableFeatherPlucking = true
	#Prevents mobs from spawning above sea level unless it's a new moon
	enablePeacefulSurface = false
	#The lowest Y-level which mobs will be prevented from spawning
	#Range: > -2147483648
	peacefulSurfaceMinY = 48
	#This controls the overall chance for V-Tweaks to attempt converting a monster to a Challenger.
	#This chance is applied before any Challenger Mob weights or entity filters.
	#Range: 0.0 ~ 1.0
	challengerMobGlobalChance = 0.25
	#Allows you to gear up tamed pets any armor and/or weapon. Doesn't render, but DOES work!
	enablePetArmory = false

#Item Tweaks
["item tweaks"]
	#Convert Concrete Powder to Concrete when the item is thrown into water
	enableConreteTweaks = true
	#Allow for modifications to item despawn timers
	enableDespawnTimeAdjustments = false
	#Adjust Item Despawn Time (in ticks: 20 ticks in a second - default despawn delay is 6000 ticks)
	#-1 prevents items from despawning at all.
	#If other "do x on despawn" configs are enabled, then those items **will still despawn**
	#Range: > -1
	despawnTimeAdjustments = 6000
	#Instead of de-spawning, saplings will attempt to plant themselves
	enableSaplingPlanting = true

