
#General options for defining sound effects
["Sound Options"]
	#Ticks between culled sound events (0 to disable culling)
	#Range: 0 ~ 6000
	"Sound Culling Interval" = 20
	#Enable sound reverb and filtering
	"Enable Enhanced Sounds" = true
	#Occlude WEATHER sounds
	"Occlude WEATHER Sounds" = false
	#Options to configure sounds on an individual basis
	"Individual Sound Config" = ["alexsmobs:cachalot_whale_click block 0", "alexsmobs:cachalot_whale_hurt block", "alexsmobs:cachalot_whale_idle block", "minecraft:entity.chicken.ambient cull", "minecraft:entity.cow.ambient cull", "minecraft:entity.ender_dragon.death cull 25", "minecraft:entity.llama.ambient cull", "minecraft:entity.pig.ambient cull", "minecraft:entity.sheep.ambient cull", "minecraft:entity.wither.death cull 25", "mobeffects:armor.crystal_foot 35", "mobeffects:armor.crystal_run 35", "mobeffects:armor.crystal_walk 35", "mobeffects:armor.heavy_foot 35", "mobeffects:armor.heavy_run 35", "mobeffects:armor.heavy_walk 35", "mobeffects:armor.light_run 35", "mobeffects:armor.light_walk 35", "mobeffects:armor.medium_foot 35", "mobeffects:armor.medium_run 35", "mobeffects:armor.medium_walk 35", "mobeffects:armor.slimey_run 35", "mobeffects:armor.slimey_walk 35"]
	#Number of background threads to handle sound effect calculations (0 is default)
	#Range: 0 ~ 8
	"Background Workers" = 0
	#Enable HRTF processing in OpenAL
	"Enable HRTF Processing" = false
	#Occlude RECORDS sounds
	"Occlude RECORDS Sounds" = false
	#Enable sound occlusion calculations (sound muffling when positioned behind blocks)
	"Enable Sound Occlusion Calculations" = true
	#Enable conversion of stereo sounds to mono format for spacial play
	"Enable Stereo to Mono Conversion" = true
	#Possible sounds to play when client reaches main game menu
	"Startup Sound List" = ["minecraft:entity.experience_orb.pickup"]
	#Number of streaming sound channels to configure
	#Range: 8 ~ 16
	"Streaming Sound Count" = 10

#Defines parameters for special effects
["Effect Options"]
	#Block range of entity special effect handling
	#Range: 16 ~ 64
	"Block Range" = 24
	#Replace client side Randomizers with faster versions
	"Replace Randoms" = true

#Defines how Sound Control logging will behave
["Logging Options"]
	#Bitmask for toggling various debug traces
	#Range: > 0
	"Debug Flag Mask" = 0
	#Enables/disables debug logging of the mod
	"Debug Logging" = false

